lcs_homepage:
    path:     /
    defaults: { _controller: LCSBundle:Accueil:index }

#### COMPETITIONS ####    

lcs_competitions_index:
    path:     /competitions
    defaults: { _controller: LCSBundle:Competition:index }
    
lcs_competitions_liste:
    path    : /competitions/liste
    defaults: { _controller: LCSBundle:Competition:liste }
    options:
        expose: true

lcs_competitions_details:
    path    : /competitions/details/{id}
    defaults: { _controller: LCSBundle:Competition:details }
    options:
        expose: true

lcs_competitions_edit:
    path    : /competitions/edit/{id}
    defaults: { _controller: LCSBundle:Competition:edit, id: null }
    options:
        expose: true

#### EQUIPES ####

lcs_equipes_index:
    path:     /equipes
    defaults: { _controller: LCSBundle:Equipe:index }
    
lcs_equipes_liste:
    path    : /equipes/liste
    defaults: { _controller: LCSBundle:Equipe:liste }
    options:
        expose: true

lcs_equipes_details:
    path    : /equipes/details/{id}
    defaults: { _controller: LCSBundle:Equipe:details }
    options:
        expose: true

lcs_equipes_edit:
    path    : /equipes/edit/{id}
    defaults: { _controller: LCSBundle:Equipe:edit, id: null }
    options:
        expose: true

#### JOUEURS ####

lcs_joueurs_index:
    path:     /joueurs
    defaults: { _controller: LCSBundle:Joueur:index }
    
lcs_joueurs_liste:
    path    : /joueurs/liste
    defaults: { _controller: LCSBundle:Joueur:liste }
    options:
        expose: true

lcs_joueurs_details:
    path    : /joueurs/details/{pseudo}
    defaults: { _controller: LCSBundle:Joueur:details }
    options:
        expose: true

#### MATCHS ####

lcs_matchs_index:
    path:     /matchs
    defaults: { _controller: LCSBundle:Game:index }

#### USERS ####

lcs_users_index:
    path:     /utilisateurs
    defaults: { _controller: LCSBundle:Utilisateur:index }

lcs_user_details:
    path:    /profil/{username}
    defaults: { _controller: LCSBundle:Utilisateur:profil}

lcs_users_liste:
    path:    /utilisateurs/liste
    defaults: { _controller: LCSBundle:Utilisateur:liste }
    options:
        expose: true

lcs_users_edit:
    path:    /utilisateurs/edit/{id}
    defaults: { _controller: LCSBundle:Utilisateur:edit, id: null }
    options:
        expose: true