lcs_homepage:
    path:     /
    defaults: { _controller: LCSBundle:Accueil:index }

lcs_competitions_index:
    path:     /competitions
    defaults: { _controller: LCSBundle:Competition:index }

lcs_equipes_index:
    path:     /equipes
    defaults: { _controller: LCSBundle:Equipe:index }

lcs_joueurs_index:
    path:     /joueurs
    defaults: { _controller: LCSBundle:Joueur:index }

lcs_matchs_index:
    path:     /matchs
    defaults: { _controller: LCSBundle:Game:index }

lcs_admin_index:
    path:     /admin
    defaults: { _controller: LCSBundle:Admin:index }