services:
#    lcs.example:
#        class: LCSBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    lcs.locale_listener:
        class: LCSBundle\EventListener\LocaleListener
        arguments: ["%kernel.default_locale%"]
        tags:
            - { name: kernel.event_subscriber }