<?php

namespace LCSBundle\Repository;

/**
 * EquipeJoueurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EquipeJoueurRepository extends \Doctrine\ORM\EntityRepository
{
}
