<?php

namespace LCSBundle\Repository;

/**
 * EquipeRemplacantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EquipeRemplacantRepository extends \Doctrine\ORM\EntityRepository
{
}
