<?php

namespace LCSBundle\Repository;

/**
 * GameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameRepository extends \Doctrine\ORM\EntityRepository
{
	public function findGamesByPoule($poule_id) {

		$qb = $this->createQueryBuilder('g')
			->where('g.poule = :grp_id')
			->setParameter('grp_id', $poule_id);

		return $qb->getQuery()->getResult();
	}
}
