<?php

namespace LCSBundle\Repository;

/**
 * PouleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PouleRepository extends \Doctrine\ORM\EntityRepository
{

	public function findPoulesCompetition($competition_id) {

		$qb = $this->createQueryBuilder('p')
			->where('p.competition = :com_id')
			->andWhere('p.type = :type')
			->orderBy('p.nom', 'ASC')
			->setParameter('com_id', $competition_id)
			->setParameter('type', 0);

		return $qb->getQuery()->getResult();
	}

}
