<?php

namespace LCSBundle\Repository;

/**
 * StatistiqueEquipeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatistiqueEquipeRepository extends \Doctrine\ORM\EntityRepository
{
}
