<?php

namespace LCSBundle\Repository;

/**
 * TourRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TourRepository extends \Doctrine\ORM\EntityRepository
{
    public function findTourByCompetitionId($competition_id) {

        $qb = $this->createQueryBuilder('t')
                ->where('t.competition = :com_id')
                ->orderBy('t.nom', 'ASC')
                ->setParameter('com_id', $competition_id);

        return $qb;//->getQuery()->getResult();
    }

}
