services:
#    user.example:
#        class: UserBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    authentication_handler:
        class:        UserBundle\Handler\AuthenticationHandler
        public: false
        #arguments:
         #   - @router
          #  - @session
        arguments:    [@router, @security.context, @fos_user.user_manager, @service_container]
    logout_handler:
        class:  UserBundle\Handler\LogoutSuccessHandler
        arguments:  [@router, @service_container]