<?php

namespace LCSBundle\DataFixtures\ORM;

use Doctrine\Common\DataFixtures\AbstractFixture;
use Doctrine\Common\DataFixtures\OrderedFixtureInterface;
use Doctrine\Common\Persistence\ObjectManager;
use Doctrine\ORM\Mapping\ClassMetadata;
use LCSBundle\Entity\Poste;

/**
 * Generated by Webonaute\DoctrineFixtureGenerator.
 *
 */
class LoadPoste extends AbstractFixture implements OrderedFixtureInterface
{

    /**
     * Set loading order.
     *
     * @return int
     */
    public function getOrder()
    {
        return 1;
    }


    /**
     * {@inheritDoc}
     */
    public function load(ObjectManager $manager)
    {
        $manager->getClassMetadata(Poste::class)->setIdGeneratorType(ClassMetadata::GENERATOR_TYPE_NONE);
    
        $item1 = new Poste();
        $this->addReference('_reference_LCSBundleEntityPoste1', $item1);
        $item1->setNom("Top");
        $item1->setShortname("TOP");

        $manager->persist($item1);

        $item2 = new Poste();
        $this->addReference('_reference_LCSBundleEntityPoste2', $item2);
        $item2->setNom("Mid");
        $item2->setShortname("MID");

        $manager->persist($item2);

        $item3 = new Poste();
        $this->addReference('_reference_LCSBundleEntityPoste3', $item3);
        $item3->setNom("Jungle");
        $item3->setShortname("JGL");

        $manager->persist($item3);

        $item4 = new Poste();
        $this->addReference('_reference_LCSBundleEntityPoste4', $item4);
        $item4->setNom("Support");
        $item4->setShortname("SUP");

        $manager->persist($item4);

        $item5 = new Poste();
        $this->addReference('_reference_LCSBundleEntityPoste5', $item5);
        $item5->setNom("ADC");
        $item5->setShortname("ADC");

        $manager->persist($item5);

    
        $manager->flush();
    }

}
