<?php

namespace LCSBundle\DataFixtures\ORM;

use LCSBundle\Entity\Joueur;
use Doctrine\Common\DataFixtures\AbstractFixture;
use Doctrine\Common\DataFixtures\OrderedFixtureInterface;
use Doctrine\Common\Persistence\ObjectManager;
use Doctrine\ORM\Mapping\ClassMetadata;
use LCSBundle\Entity\Poste;
use LCSBundle\Entity\Rang;

/**
 * Generated by Webonaute\DoctrineFixtureGenerator.
 *
 */
class LoadRang extends AbstractFixture implements OrderedFixtureInterface
{

    /**
     * Set loading order.
     *
     * @return int
     */
    public function getOrder()
    {
        return 2;
    }


    /**
     * {@inheritDoc}
     */
    public function load(ObjectManager $manager)
    {
        $manager->getClassMetadata(Rang::class)->setIdGeneratorType(ClassMetadata::GENERATOR_TYPE_NONE);
    
        $item1 = new Rang();
        $this->addReference('_reference_LCSBundleEntityRang1', $item1);
        $item1->setNom("Unranked");
        $item1->setCouleur("#FFFFFF");
        $item1->setValeur(0);

        $manager->persist($item1);

        $item2 = new Rang();
        $this->addReference('_reference_LCSBundleEntityRang2', $item2);
        $item2->setNom("Bronze");
        $item2->setCouleur("#7F6000");
        $item2->setValeur(1);

        $manager->persist($item2);

        $item3 = new Rang();
        $this->addReference('_reference_LCSBundleEntityRang3', $item3);
        $item3->setNom("Silver");
        $item3->setCouleur("#CCCCCC");
        $item3->setValeur(2);

        $manager->persist($item3);

        $item4 = new Rang();
        $this->addReference('_reference_LCSBundleEntityRang4', $item4);
        $item4->setNom("Gold");
        $item4->setCouleur("#F1C232");
        $item4->setValeur(3);

        $manager->persist($item4);

        $item5 = new Rang();
        $this->addReference('_reference_LCSBundleEntityRang5', $item5);
        $item5->setNom("Platine");
        $item5->setCouleur("#00FFFF");
        $item5->setValeur(4);

        $manager->persist($item5);

        $item6 = new Rang();
        $this->addReference('_reference_LCSBundleEntityRang6', $item6);
        $item6->setNom("Diamant");
        $item6->setCouleur("#4A86E8");
        $item6->setValeur(5);

        $manager->persist($item6);

    
        $manager->flush();

        $item1 = new Poste();
        $this->addReference('_reference_LCSBundleEntityPoste1', $item1);
        $item1->setNom("Top");
        $item1->setShortname("TOP");

        $manager->persist($item1);

        $item2 = new Poste();
        $this->addReference('_reference_LCSBundleEntityPoste2', $item2);
        $item2->setNom("Mid");
        $item2->setShortname("MID");

        $manager->persist($item2);

        $item3 = new Poste();
        $this->addReference('_reference_LCSBundleEntityPoste3', $item3);
        $item3->setNom("Jungle");
        $item3->setShortname("JGL");

        $manager->persist($item3);

        $item4 = new Poste();
        $this->addReference('_reference_LCSBundleEntityPoste4', $item4);
        $item4->setNom("Support");
        $item4->setShortname("SUP");

        $manager->persist($item4);

        $item5 = new Poste();
        $this->addReference('_reference_LCSBundleEntityPoste5', $item5);
        $item5->setNom("ADC");
        $item5->setShortname("ADC");

        $manager->persist($item5);

        $item6 = new Poste();
        $this->addReference('_reference_LCSBundleEntityPoste6', $item6);
        $item6->setNom("Aucun");
        $item6->setShortname("");

        $manager->persist($item6);

    
        $manager->flush();
    }

}

/**
 * Generated by Webonaute\DoctrineFixtureGenerator.
 *
 */
class LoadPosteRangJoueur extends AbstractFixture implements OrderedFixtureInterface
{

    /**
     * Set loading order.
     *
     * @return int
     */
    public function getOrder()
    {
        return 1;
    }


    /**
     * {@inheritDoc}
     */
    public function load(ObjectManager $manager)
    {
        $manager->getClassMetadata(Poste::class)->setIdGeneratorType(ClassMetadata::GENERATOR_TYPE_NONE);
    
        $item1 = new Poste();
        $this->addReference('_reference_LCSBundleEntityPoste1', $item1);
        $item1->setNom("Top");
        $item1->setShortname("TOP");

        $manager->persist($item1);

        $item2 = new Poste();
        $this->addReference('_reference_LCSBundleEntityPoste2', $item2);
        $item2->setNom("Mid");
        $item2->setShortname("MID");

        $manager->persist($item2);

        $item3 = new Poste();
        $this->addReference('_reference_LCSBundleEntityPoste3', $item3);
        $item3->setNom("Jungle");
        $item3->setShortname("JGL");

        $manager->persist($item3);

        $item4 = new Poste();
        $this->addReference('_reference_LCSBundleEntityPoste4', $item4);
        $item4->setNom("Support");
        $item4->setShortname("SUP");

        $manager->persist($item4);

        $item5 = new Poste();
        $this->addReference('_reference_LCSBundleEntityPoste5', $item5);
        $item5->setNom("ADC");
        $item5->setShortname("ADC");

        $manager->persist($item5);

        $item6 = new Poste();
        $this->addReference('_reference_LCSBundleEntityPoste6', $item6);
        $item6->setNom("Aucun");
        $item6->setShortname("");

        $manager->persist($item6);

    
        $manager->flush();

        $item8 = new Joueur();
        $this->addReference('_reference_LCSBundleEntityJoueur8', $item8);
        $item8->setPseudo("ThePowerVoid");
        $item8->setNom("Vannier");
        $item8->setPrenom("Pierre");
        $item8->setPoste($this->getReference('_reference_Proxies__CG__LCSBundleEntityPoste3'));
        $item8->setRang($this->getReference('_reference_Proxies__CG__LCSBundleEntityRang4'));

        $manager->persist($item8);

        $item13 = new Joueur();
        $this->addReference('_reference_LCSBundleEntityJoueur13', $item13);
        $item13->setPseudo("Spk Angelus");
        $item13->setNom("Lopez");
        $item13->setPrenom("Rémi");
        $item13->setPoste($this->getReference('_reference_Proxies__CG__LCSBundleEntityPoste1'));
        $item13->setRang($this->getReference('_reference_Proxies__CG__LCSBundleEntityRang3'));

        $manager->persist($item13);

        $item14 = new Joueur();
        $this->addReference('_reference_LCSBundleEntityJoueur14', $item14);
        $item14->setPseudo("Toutruche");
        $item14->setNom("Mazel");
        $item14->setPrenom("Guilhem");
        $item14->setPoste($this->getReference('_reference_Proxies__CG__LCSBundleEntityPoste5'));
        $item14->setRang($this->getReference('_reference_Proxies__CG__LCSBundleEntityRang6'));

        $manager->persist($item14);

        $item15 = new Joueur();
        $this->addReference('_reference_LCSBundleEntityJoueur15', $item15);
        $item15->setPseudo("Howrus");
        $item15->setNom("Morandini");
        $item15->setPrenom("Eric");
        $item15->setPoste($this->getReference('_reference_Proxies__CG__LCSBundleEntityPoste2'));
        $item15->setRang($this->getReference('_reference_Proxies__CG__LCSBundleEntityRang4'));

        $manager->persist($item15);

        $item16 = new Joueur();
        $this->addReference('_reference_LCSBundleEntityJoueur16', $item16);
        $item16->setPseudo("Not Known");
        $item16->setNom("Cisterne");
        $item16->setPrenom("Clément");
        $item16->setPoste($this->getReference('_reference_Proxies__CG__LCSBundleEntityPoste4'));
        $item16->setRang($this->getReference('_reference_Proxies__CG__LCSBundleEntityRang4'));

        $manager->persist($item16);

    
        $manager->flush();
    }

}