<?php

namespace LCSBundle\DataFixtures\ORM;

use Doctrine\Common\DataFixtures\AbstractFixture;
use Doctrine\Common\DataFixtures\OrderedFixtureInterface;
use Doctrine\Common\Persistence\ObjectManager;
use Doctrine\ORM\Mapping\ClassMetadata;
use LCSBundle\Entity\Joueur;

/**
 * Generated by Webonaute\DoctrineFixtureGenerator.
 *
 */
class LoadJoueur extends AbstractFixture implements OrderedFixtureInterface
{

    /**
     * Set loading order.
     *
     * @return int
     */
    public function getOrder()
    {
        return 3;
    }


    /**
     * {@inheritDoc}
     */
    public function load(ObjectManager $manager)
    {
        $manager->getClassMetadata(Joueur::class)->setIdGeneratorType(ClassMetadata::GENERATOR_TYPE_NONE);
    
        $item8 = new Joueur();
        $this->addReference('_reference_LCSBundleEntityJoueur8', $item8);
        $item8->setPseudo("ThePowerVoid");
        $item8->setNom("Vannier");
        $item8->setPrenom("Pierre");
        $item8->setPoste($this->getReference('_reference_LCSBundleEntityPoste3'));
        $item8->setRang($this->getReference('_reference_LCSBundleEntityRang4'));

        $manager->persist($item8);

        $item13 = new Joueur();
        $this->addReference('_reference_LCSBundleEntityJoueur13', $item13);
        $item13->setPseudo("Spk Angelus");
        $item13->setNom("Lopez");
        $item13->setPrenom("Rémi");
        $item13->setPoste($this->getReference('_reference_LCSBundleEntityPoste1'));
        $item13->setRang($this->getReference('_reference_LCSBundleEntityRang3'));

        $manager->persist($item13);

        $item14 = new Joueur();
        $this->addReference('_reference_LCSBundleEntityJoueur14', $item14);
        $item14->setPseudo("Toutruche");
        $item14->setNom("Mazel");
        $item14->setPrenom("Guilhem");
        $item14->setPoste($this->getReference('_reference_LCSBundleEntityPoste5'));
        $item14->setRang($this->getReference('_reference_LCSBundleEntityRang6'));

        $manager->persist($item14);

        $item15 = new Joueur();
        $this->addReference('_reference_LCSBundleEntityJoueur15', $item15);
        $item15->setPseudo("Howrus");
        $item15->setNom("Morandini");
        $item15->setPrenom("Eric");
        $item15->setPoste($this->getReference('_reference_LCSBundleEntityPoste2'));
        $item15->setRang($this->getReference('_reference_LCSBundleEntityRang4'));

        $manager->persist($item15);

        $item16 = new Joueur();
        $this->addReference('_reference_LCSBundleEntityJoueur16', $item16);
        $item16->setPseudo("Not Known");
        $item16->setNom("Cisterne");
        $item16->setPrenom("Clément");
        $item16->setPoste($this->getReference('_reference_LCSBundleEntityPoste4'));
        $item16->setRang($this->getReference('_reference_LCSBundleEntityRang4'));

        $manager->persist($item16);

    
        $manager->flush();
    }

}
