<?php

namespace LCSBundle\DataFixtures\ORM;

use Doctrine\Common\DataFixtures\AbstractFixture;
use Doctrine\Common\DataFixtures\OrderedFixtureInterface;
use Doctrine\Common\Persistence\ObjectManager;
use Doctrine\ORM\Mapping\ClassMetadata;
use LCSBundle\Entity\Equipe;

/**
 * Generated by Webonaute\DoctrineFixtureGenerator.
 *
 */
class LoadEquipe extends AbstractFixture implements OrderedFixtureInterface
{

    /**
     * Set loading order.
     *
     * @return int
     */
    public function getOrder()
    {
        return 5;
    }


    /**
     * {@inheritDoc}
     */
    public function load(ObjectManager $manager)
    {
        $manager->getClassMetadata(Equipe::class)->setIdGeneratorType(ClassMetadata::GENERATOR_TYPE_NONE);
    
        $item1 = new Equipe();
        $this->addReference('_reference_LCSBundleEntityEquipe1', $item1);
        $item1->setNom("Flash-in");
        $item1->setCapitaine($this->getReference('_reference_LCSBundleEntityJoueur1'));

        $manager->persist($item1);

    
        $manager->flush();
    }

}
